<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F1jOqKxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f1jOqKx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f1jOqKx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'plat' => ['privates', '.errored..service_locator.f1jOqKx.App\\Entity\\Plat', NULL, 'Cannot autowire service ".service_locator.f1jOqKx": it references class "App\\Entity\\Plat" but no such service exists.'],
            'platRepository' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'plat' => 'App\\Entity\\Plat',
            'platRepository' => 'App\\Repository\\PlatRepository',
        ]);
    }
}
