<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XGgS2UZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xGgS2UZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xGgS2UZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formule' => ['privates', '.errored..service_locator.xGgS2UZ.App\\Entity\\Formule', NULL, 'Cannot autowire service ".service_locator.xGgS2UZ": it references class "App\\Entity\\Formule" but no such service exists.'],
            'formuleRepository' => ['privates', 'App\\Repository\\FormuleRepository', 'getFormuleRepositoryService', true],
        ], [
            'formule' => 'App\\Entity\\Formule',
            'formuleRepository' => 'App\\Repository\\FormuleRepository',
        ]);
    }
}
