<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CUlN4D1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cUlN4D1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cUlN4D1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeAEmporter' => ['privates', '.errored..service_locator.cUlN4D1.App\\Entity\\CommandeAEmporter', NULL, 'Cannot autowire service ".service_locator.cUlN4D1": it references class "App\\Entity\\CommandeAEmporter" but no such service exists.'],
            'commandeAEmporterRepository' => ['privates', 'App\\Repository\\CommandeAEmporterRepository', 'getCommandeAEmporterRepositoryService', true],
        ], [
            'commandeAEmporter' => 'App\\Entity\\CommandeAEmporter',
            'commandeAEmporterRepository' => 'App\\Repository\\CommandeAEmporterRepository',
        ]);
    }
}
