<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HhXDO5PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HhXDO5P' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HhXDO5P'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeAEmporter' => ['privates', '.errored..service_locator.HhXDO5P.App\\Entity\\CommandeAEmporter', NULL, 'Cannot autowire service ".service_locator.HhXDO5P": it references class "App\\Entity\\CommandeAEmporter" but no such service exists.'],
        ], [
            'commandeAEmporter' => 'App\\Entity\\CommandeAEmporter',
        ]);
    }
}
