<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1IVig7ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1IVig7Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1IVig7Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'platJourRepository' => ['privates', 'App\\Repository\\PlatJourRepository', 'getPlatJourRepositoryService', true],
        ], [
            'fileUploader' => 'App\\Service\\FileUploader',
            'platJourRepository' => 'App\\Repository\\PlatJourRepository',
        ]);
    }
}
