<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__VHq7udService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..VHq7ud' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..VHq7ud'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeAEmporterRepository' => ['privates', 'App\\Repository\\CommandeAEmporterRepository', 'getCommandeAEmporterRepositoryService', true],
        ], [
            'commandeAEmporterRepository' => 'App\\Repository\\CommandeAEmporterRepository',
        ]);
    }
}
