<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeAEmporter2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.cUlN4D1.App\Entity\CommandeAEmporter' shared service.
     *
     * @return \App\Entity\CommandeAEmporter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.cUlN4D1": it references class "App\\Entity\\CommandeAEmporter" but no such service exists.');
    }
}
