<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatJourService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PoX3trZ.App\Entity\PlatJour' shared service.
     *
     * @return \App\Entity\PlatJour
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PoX3trZ": it references class "App\\Entity\\PlatJour" but no such service exists.');
    }
}
