<?php

namespace ContainerG0OV6wm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.f1jOqKx.App\Entity\Plat' shared service.
     *
     * @return \App\Entity\Plat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.f1jOqKx": it references class "App\\Entity\\Plat" but no such service exists.');
    }
}
