<?php

namespace Container205B4BR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__186m20Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..186m20' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..186m20'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categoryRepository' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'formuleRepository' => ['privates', 'App\\Repository\\FormuleRepository', 'getFormuleRepositoryService', true],
            'platJourRepository' => ['privates', 'App\\Repository\\PlatJourRepository', 'getPlatJourRepositoryService', true],
            'platRepository' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'categoryRepository' => 'App\\Repository\\CategoryRepository',
            'formuleRepository' => 'App\\Repository\\FormuleRepository',
            'platJourRepository' => 'App\\Repository\\PlatJourRepository',
            'platRepository' => 'App\\Repository\\PlatRepository',
        ]);
    }
}
