<?php

namespace Container205B4BR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S8n88efService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.S8n88ef' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.S8n88ef'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'adminReservation' => ['privates', '.errored..service_locator.S8n88ef.App\\Entity\\AdminReservation', NULL, 'Cannot autowire service ".service_locator.S8n88ef": it references class "App\\Entity\\AdminReservation" but no such service exists.'],
            'adminReservationRepository' => ['privates', 'App\\Repository\\AdminReservationRepository', 'getAdminReservationRepositoryService', true],
        ], [
            'adminReservation' => 'App\\Entity\\AdminReservation',
            'adminReservationRepository' => 'App\\Repository\\AdminReservationRepository',
        ]);
    }
}
