<?php

namespace Container205B4BR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YKl6MqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y_kl6Mq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y_kl6Mq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'platJour' => ['privates', '.errored..service_locator.Y_kl6Mq.App\\Entity\\PlatJour', NULL, 'Cannot autowire service ".service_locator.Y_kl6Mq": it references class "App\\Entity\\PlatJour" but no such service exists.'],
        ], [
            'platJour' => 'App\\Entity\\PlatJour',
        ]);
    }
}
