<?php

namespace Container205B4BR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QSrR5OFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qSrR5OF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qSrR5OF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'platJourRepository' => ['privates', 'App\\Repository\\PlatJourRepository', 'getPlatJourRepositoryService', true],
            'platRepository' => ['privates', 'App\\Repository\\PlatRepository', 'getPlatRepositoryService', true],
        ], [
            'platJourRepository' => 'App\\Repository\\PlatJourRepository',
            'platRepository' => 'App\\Repository\\PlatRepository',
        ]);
    }
}
