<?php

namespace Container205B4BR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeAEmporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HhXDO5P.App\Entity\CommandeAEmporter' shared service.
     *
     * @return \App\Entity\CommandeAEmporter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HhXDO5P": it references class "App\\Entity\\CommandeAEmporter" but no such service exists.');
    }
}
