<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container205B4BR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container205B4BR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container205B4BR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container205B4BR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container205B4BR\App_KernelDevDebugContainer([
    'container.build_hash' => '205B4BR',
    'container.build_id' => '699143bb',
    'container.build_time' => 1661327116,
], __DIR__.\DIRECTORY_SEPARATOR.'Container205B4BR');
